---
title: "Step 4.1 Merge all samples by Seurat Harmony"
author: "Zhang Yongchao"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    number_sections: TRUE
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      collapse = TRUE,
                      warning = FALSE)
```

Method Refer:

>[Seurat](https://satijalab.org/seurat/)

>[SeuratWrappers](https://github.com/satijalab/seurat-wrappers)

>[Integration of datasets using Harmony](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/harmony.html)

**Parameters:**

```{r}
Results.dir <- "./4.1-Merged-Rds"
```


```{r}
suppressMessages(library(dplyr)) 
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(cowplot))
suppressMessages(library(ggplot2))
suppressMessages(library(ggpubr))
suppressMessages(library(clustree))
suppressMessages(library(harmony))
# suppressMessages(library(scater))
suppressMessages(library(DT))
```


# Merge and Relevel all samples

```{r}
immune.combined <- readRDS("./Merge-All-Embryo-SeuratHarmony.rds")
```

```{r}
Idents(immune.combined) <- "Merged_SCVI_RNA_snn_res.0.8"
DimPlot(immune.combined, reduction = "scviumap",label = TRUE)
DimPlot(immune.combined, reduction = "umap",label = TRUE)
```


# subset mesen

```{r}
immune.combined <- subset(immune.combined, idents = c(5,9,13,24,10,16,17,20,25,26,27), invert = TRUE)
DimPlot(immune.combined, reduction = "scviumap",label = TRUE)
```
```{r}
plot <- DimPlot(object = immune.combined,reduction = "scviumap")
plot + 
  geom_hline(yintercept=-9, linetype="dashed", color = "red", size=1) +
  geom_vline(xintercept=-5.6, linetype="dashed", color = "red", size=1)
embedding <- plot$data
embedding <- embedding[embedding$scviumap_1 > -5.6 & embedding$scviumap_2 > -9,]
# Automatically set the identity class of selected cells and return a new Seurat object
immune.combined <- subset(immune.combined, cells = rownames(embedding))
DimPlot(immune.combined, reduction = "scviumap")
```

```{r}
immune.combined@reductions$harmony <- NULL
immune.combined@reductions$scvi <- NULL
immune.combined@reductions$scviumap <- NULL
immune.combined@reductions$scvitsne <- NULL
```

## Perform an integrated analysis

```{r}
# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(immune.combined, split.by = "orig.ident")

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = ifnb.list)
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE, npcs = 40) # if set npcs=50, will throw out an error!
})
```


```{r}
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features, reduction = "rpca")
# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)
DefaultAssay(immune.combined) <- "integrated"
```
```{r fig.width=18,fig.height=7}
# Remove mito genes from variable gnes
# grep("^mt-",VariableFeatures(immune.combined),value = TRUE)
# VariableFeatures(immune.combined) <- grep("^mt-",VariableFeatures(immune.combined),value = TRUE,invert = TRUE)
## Remove Cell Cycle-Related Genes
# VariableFeatures(immune.combined) <- VariableFeatures(immune.combined)[! VariableFeatures(immune.combined) %in% c(s.genes,g2m.genes)]
# length(VariableFeatures(immune.combined))
# Remove sex related genes
# if ("Xist" %in% VariableFeatures(immune.combined)) {
#   VariableFeatures(immune.combined) <- VariableFeatures(immune.combined)[VariableFeatures(immune.combined) != "Xist"]
# }

# # Identify the 10 most highly variable genes
# top10 <- head(VariableFeatures(immune.combined), 10)
# # plot variable features with and without labels
# plot1 <- VariableFeaturePlot(immune.combined)
# plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
# plot1 + plot2
```

```{r  fig.height=6,fig.width=7}
# immune.combined <- ScaleData(immune.combined, vars.to.regress = c("S.Score", "G2M.Score","percent.mt","nCount_RNA"), 
#                              features = VariableFeatures(immune.combined), verbose = FALSE, assay = DefaultAssay(immune.combined))
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 50, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- RunTSNE(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30) %>% 
  FindClusters(resolution = c(0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6))
```


# Cell numbers in each resolution

```{r}
# statics.cluster.cells <- function(seurat, keys = "(_snn_res)|(^Annotation)"){
#   test.data <- as.data.frame(as.matrix(seurat@meta.data[, grepl(keys,colnames(seurat@meta.data))]),stringsAsFactors = FALSE)
#   test.data$cell <- rownames(test.data)
#   rownames(test.data) <- NULL
#   test.data.melt <- reshape2::melt(test.data, id.vars = "cell",value.name = "cluster")
#   test.data.melt.dcast <- reshape2::dcast(test.data.melt,formula = cluster ~ variable,fun.aggregate = length)
#   test.data.melt.dcast$cluster <- as.numeric(test.data.melt.dcast$cluster)
#   test.data.melt.dcast <- arrange(test.data.melt.dcast,cluster)
#   rownames(test.data.melt.dcast) <- test.data.melt.dcast$cluster
#   test.data.melt.dcast$cluster <- NULL
#   return(test.data.melt.dcast)
# }
# DT::datatable(statics.cluster.cells(immune.combined, keys = paste("(^",DefaultAssay(immune.combined),"_snn_res)|(^Annotation)",sep = "")),  extensions = c('Buttons','ColReorder','FixedColumns'),
#               options = list(pageLength = 40, 
#                              autoWidth = TRUE,
#                              scrollX = TRUE,
#                              scrollY = FALSE,
#                              dom = 'Bfrtip', # Buttons | note B in dom denotes the place where the buttons are to be inserted
#                              buttons = c('csv', 'pdf'),
#                              colReorder = TRUE,
#                              fixedColumns = TRUE)
#               )
```

# Choose Resolution

```{r fig.height=10,fig.width=10}
# clustree(immune.combined@meta.data,prefix = paste(DefaultAssay(immune.combined),"_snn_res.",sep = ""))
```

```{r}
cluster.resolution <- paste(DefaultAssay(immune.combined),"_snn_res.0.6",sep = "")
# cluster.resolution <- "RNA_snn_res.0.6"
Idents(immune.combined) <- cluster.resolution
```

```{r fig.width=8,fig.height=6}
DimPlot(immune.combined,label = TRUE)
DimPlot(immune.combined,label = TRUE,reduction = "tsne")

DimPlot(immune.combined,group.by = "orig.ident")
DimPlot(immune.combined,reduction = "tsne",group.by = "orig.ident")

DimPlot(immune.combined,group.by = "day")
DimPlot(immune.combined,reduction = "tsne",group.by = "day")
```

```{r fig.width=6,fig.height=5}
DimPlot(immune.combined,group.by = "Phase")
DimPlot(immune.combined,reduction = "tsne",group.by = "Phase")
```

```{r fig.height=6,fig.width=13}
DimPlot(immune.combined,label = TRUE,split.by = "day",ncol = 4)
```

# Top expressed genes in each cluster

```{r fig.width=6,fig.height=6}
# for (i in levels(immune.combined@active.ident)) {
#   print(plotHighestExprs(as.SingleCellExperiment(subset(immune.combined,idents = i),assay = DefaultAssay(immune.combined)),colour_cells_by = cluster.resolution))
# }
```

```{r}
# expr.ave <- AverageExpression(immune.combined, assays = DefaultAssay(immune.combined))[[1]]
# expr.ave$gene <- rownames(expr.ave)
# expr.ave.melt <- reshape2::melt(expr.ave,id.vars = "gene", value.name = "expr",variable.name = "cluster")
# top_20_genes <- expr.ave.melt %>%
#   group_by(cluster) %>%
#   top_n(20,expr) %>%
#   arrange(cluster,desc(expr))
# 
# DT::datatable(top_20_genes,  extensions = c('Buttons','ColReorder','FixedColumns'),
#               options = list(pageLength = 20, 
#                              autoWidth = TRUE,
#                              scrollX = FALSE,
#                              scrollY = FALSE,
#                              dom = 'Bfrtip', # Buttons | note B in dom denotes the place where the buttons are to be inserted
#                              buttons = c('csv', 'pdf'),
#                              colReorder = FALSE,
#                              fixedColumns = FALSE)
#               )
```

# Top expressed genes in each time point

```{r fig.width=6,fig.height=6}
# Idents(immune.combined) <- "day"
# for (i in levels(immune.combined@active.ident)) {
#   print(plotHighestExprs(as.SingleCellExperiment(subset(immune.combined, day == i),assay = DefaultAssay(immune.combined)),colour_cells_by = "day"))
# }

```

```{r}
# expr.ave <- AverageExpression(immune.combined, assays = DefaultAssay(immune.combined))[[1]]
# expr.ave$gene <- rownames(expr.ave)
# expr.ave.melt <- reshape2::melt(expr.ave,id.vars = "gene", value.name = "expr",variable.name = "cluster")
# top_20_genes <- expr.ave.melt %>%
#   group_by(cluster) %>%
#   top_n(20,expr) %>%
#   arrange(cluster,desc(expr))
# 
# DT::datatable(top_20_genes,  extensions = c('Buttons','ColReorder','FixedColumns'),
#               options = list(pageLength = 20, 
#                              autoWidth = TRUE,
#                              scrollX = FALSE,
#                              scrollY = FALSE,
#                              dom = 'Bfrtip', # Buttons | note B in dom denotes the place where the buttons are to be inserted
#                              buttons = c('csv', 'pdf'),
#                              colReorder = FALSE,
#                              fixedColumns = FALSE)
#               )
# Idents(immune.combined) <- cluster.resolution
```


# Cluster QC

```{r fig.width=20,fig.height=10}
markers <- c("Pdgfra","Epcam","Ptprc","Vwf","Pdgfrb","Nrxn1",'Rgs5','Acta2','Cd34','Il33','Il1rl1','Lgr5')
qc.keys <- colnames(immune.combined@meta.data)[2:6]
VlnPlot(immune.combined,features = qc.keys, pt.size = 0, ncol = 3) + NoLegend()
VlnPlot(immune.combined,features = markers, pt.size = 0, ncol = 3) + NoLegend()
```

```{r fig.height=12,fig.width=15}
VlnPlot(immune.combined,features = qc.keys, pt.size = 0, ncol = 3, group.by = "day") + NoLegend()
VlnPlot(immune.combined,features = qc.keys, group.by = "day",pt.size = 0)  + NoLegend()
```

```{r fig.width=17,fig.height=12}
FeaturePlot(immune.combined,features = markers) & NoLegend()
```

```{r fig.width=12,fig.height=14}
FeaturePlot(immune.combined,features = qc.keys)
```


# save data

```{r}
if ( !dir.exists(Results.dir)) {
  dir.create(Results.dir,recursive = TRUE)
}
DefaultAssay(immune.combined) <- 'RNA'
sampleName <- "subset"
saveRDS(immune.combined, file = paste(Results.dir,"/",sampleName,".rds",sep = ""))
```

