---
title: "Step4.0 Batch QC of the Raw Rds files"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    number_sections: TRUE
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  collapse = TRUE,
  fig.align = "center")
```

>[Exploring a Poor Quality Sample](https://github.com/hbctraining/scRNA-seq_online/blob/master/lessons/QC_bad_data.md)

```{r}
Single.dir <- "../../SingleSample/"
assay.use <- "RNA"
prefix.removed <- "" # prefix in orig.ident to be removed, such as: "APCmin_Mouse_Colon_"
Raw.rds.dir <- "/3.1-QC-Passed-Cells-Rds"
qc.full.path <- "3.1-QC-Passed-Cells-Rds/qc.statics.csv"
```

```{r}
suppressMessages(library(dplyr)) 
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(ggridges))
suppressMessages(library(knitr))
suppressMessages(library(DT))
```

# import and merge all samples

```{r}
#AnalysisDirs <- grep("Colon",list.dirs("../Single-Sample/Cellbender-Seurat-Scrublet",recursive = FALSE,full.names = TRUE),value = TRUE)
AnalysisDirs <- list.dirs(Single.dir,recursive = FALSE,full.names = TRUE)
rds.files <- list.files(paste(AnalysisDirs,Raw.rds.dir,sep = ""),pattern = "rds$",full.names = TRUE)
basename(rds.files)
```
```{r}
# only keep embryo samples
rds.files <- grep("E_SI_", rds.files, value = TRUE)
basename(rds.files)
```



```{r}
obj.list <- lapply(rds.files, function(pbmc){
  # message("* Processing sample: ",pbmc)
  cds <- readRDS(pbmc)
  # message("Project Name is ", cds@project.name)
  ## Remove cells with zero UMI counts
  # Attention, some cells has zero CellBender revised UMI counts. This is a bug in cellbender step.
  cells.kept <- colnames(cds)[cds@meta.data[,paste("nCount", assay.use,sep = "_")] > 0]
  cds <- subset(cds, cells = cells.kept)
  return(cds)
})
# obj.list
```


# Merge and Relevel all samples

```{r}
immune.combined <- merge(obj.list[[1]], obj.list[-1])
DefaultAssay(immune.combined) <- assay.use
```


# Vlnplot of QC markers

```{r fig.width=24,fig.height=6}
qc.keys <- c(colnames(immune.combined@meta.data)[2:6])
VlnPlot(immune.combined, features = qc.keys, ncol = 5,group.by = "orig.ident",pt.size = 0)
```


## Cell Counts

```{r}
df <- immune.combined@meta.data
ggplot(df, aes(x=orig.ident, fill=orig.ident)) +
  geom_bar(stat="Count") +
  theme_minimal() +
  geom_hline(aes(yintercept=3000),linetype = "dashed") +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

# UMI counts per cell

```{r}
ggplot(df, aes(x = nCount_RNA, y = orig.ident, fill = orig.ident)) +
	geom_density_ridges(alpha = 0.7) +
	theme_ridges() + 
  scale_x_log10() +
  geom_vline(aes(xintercept=2000),linetype = "dashed") +
  geom_vline(aes(xintercept=3000),linetype = "dashed") +
	theme(legend.position = "none")
```

# Genes detected per cell

```{r}
ggplot(df, aes(x = nFeature_RNA , y = orig.ident, fill = orig.ident)) +
	geom_density_ridges(alpha = 0.7) +
	theme_ridges() + 
  scale_x_log10() +
  geom_vline(aes(xintercept=1000),linetype = "dashed") +
  geom_vline(aes(xintercept=1500),linetype = "dashed") +
  geom_vline(aes(xintercept=5000),linetype = "dashed") +
	theme(legend.position = "none")
```


# UMIs vs. genes detected


```{r fig.width=19,fig.height=15}
df %>% 
  	ggplot(aes(x=nCount_RNA, y=nFeature_RNA, color=percent.mt > 20)) + 
  	geom_point(alpha = 0.5,size = 0.1) + 
  	stat_smooth(method=lm) +
  	scale_x_log10() + 
  	scale_y_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 1000,linetype = "dashed") +
  	geom_hline(yintercept = 500,linetype = "dashed") +
    facet_wrap(~orig.ident)
```

```{r}
ggplot(df, aes(x = percent.mt + 1, y = orig.ident, fill = orig.ident)) +
	geom_density_ridges(alpha = 0.7) +
	theme_ridges() + 
  scale_x_log10() +
  geom_vline(aes(xintercept=11),linetype = "dashed") +
  geom_vline(aes(xintercept=13),linetype = "dashed") +
	theme(legend.position = "none")
```

# Novelty

```{r}
ggplot(df, aes(x = log10GenesPerUMI, y = orig.ident, fill = orig.ident)) +
	geom_density_ridges(alpha = 0.7) +
	theme_ridges() + 
  scale_x_log10() +
  geom_vline(aes(xintercept=0.8),linetype = "dashed") +
	theme(legend.position = "none")
```

# Filtered results

```{r}
QC.Cut <- function(SeuratObj){
  sample.meta <- 
    SeuratObj@meta.data %>%
    select("orig.ident","nCount_RNA","nFeature_RNA","percent.mt","log10GenesPerUMI") %>%
    mutate(nCount_RNA = nCount_RNA > 3000 & nCount_RNA < 5e4,
            nFeature_RNA = nFeature_RNA > 1000,
            percent.mt = percent.mt < 10,
            log10GenesPerUMI = log10GenesPerUMI > 0.8)
  sample.statics <- 
    sample.meta %>%
    group_by(orig.ident) %>%
    summarise(nCount_RNA = sum(!nCount_RNA),
            nFeature_RNA = sum(!nFeature_RNA),
            percent.mt = sum(!percent.mt),
            log10GenesPerUMI = sum(!log10GenesPerUMI),
            cell.raw = n())
  sample.meta.keep <- as.data.frame.matrix(table(sample.meta$orig.ident, unname(apply(sample.meta[,2:5],1,all))))
  sample.info <- cbind(sample.statics,sample.meta.keep)
  colnames(sample.info)[6:7] <- c("cells.removed","cells.kept")
  sample.info
}
kable(QC.Cut(immune.combined),caption = "Statics using unified cutoff")
```

# QC cutoffs used and the effects


```{r}
#AnalysisDirs <- grep("Colon",list.dirs("../Single-Sample/Cellbender-Seurat-Scrublet",recursive = FALSE,full.names = TRUE),value = TRUE)
AnalysisDirs <- list.dirs(Single.dir,recursive = FALSE,full.names = TRUE)
qc.files <- paste(AnalysisDirs,qc.full.path,sep = "/")
qc.files
```
```{r}
qc.csv <- lapply(qc.files,function(x){
  read.csv(x,stringsAsFactors = FALSE)
})
qc.res <- Reduce(rbind,qc.csv)
qc.res <- qc.res[,-1]
DT::datatable(qc.res,  extensions = c('Buttons','ColReorder','FixedColumns'),
              options = list(pageLength = 30, 
                             autoWidth = TRUE,
                             scrollX = TRUE,
                             scrollY = FALSE,
                             dom = 'Bfrtip', # Buttons | note B in dom denotes the place where the buttons are to be inserted
                             buttons = c('csv', 'pdf'),
                             colReorder = TRUE,
                             fixedColumns = TRUE)
              )
```

# Session info

```{r}
sessionInfo()
```


