---
title: "DEGs-Subset"
author: "Zhang Yongchao"
date: "November 19, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = -1,
                      message = -1)
```


```{r}
all.samples <- c("D135","D145")
```

```{r}
library(Seurat)
library(ggplot2)
library(DT)
```

```{r fig.width=6,fig.height=6}
cds <- readRDS("../../Merge-Total-SeuratHarmony.rds")
DimPlot(cds,label = TRUE) + NoLegend()
```

```{r fig.width=6,fig.height=6}
cds.subset <- subset(cds,idents = c(2,3,9,13,25,33))
DimPlot(cds.subset,label = TRUE) + NoLegend()
```

```{r fig.width=17,fig.height = 3}
DimPlot(cds.subset,split.by = "day",label = TRUE) + NoLegend()
```
```{r fig.width=12,fig.height=3}
Idents(cds.subset) <- cds.subset@meta.data$day
DimPlot(cds.subset,split.by = "day",label = TRUE) + NoLegend()
```


```{r}
species <- "mouse" # or human, mouse
kegg.organism <- switch(species,
                        drosophlia = "dme",
                        human = "hsa",
                        mouse = "mmu")
org.db <- switch(species,
                 drosophlia = "org.Dm.eg.db",
                 human = "org.Hs.eg.db",
                 mouse = "org.Mm.eg.db")
```

```{r}
suppressMessages(library(dplyr))
suppressMessages(library(clusterProfiler))
switch (species,
  drosophlia = suppressMessages(library(org.Dm.eg.db)),
  human = suppressMessages(library(org.Hs.eg.db)),
  mouse = suppressMessages(library(org.Mm.eg.db))
)
suppressMessages(library(pathview))
suppressMessages(library(filesstrings))
```

# Plots: GO And KEGG

```{r fig.width=12,fig.height=6}
for ( i in 1:length(all.samples) ) {
  if(i < length(all.samples)){
    for (j in (i+1):length(all.samples)) {
      sample1 <- all.samples[i]
      sample2 <- all.samples[j]
      pair.name <- paste(sample1,"-vs-",sample2,sep = "")
      
      #  DEGs
      DEGs <- FindMarkers(cds.subset, ident.1 = sample1, ident.2 = sample2)
      print(datatable(DEGs))
      write.csv(DEGs,file = paste("DEGs-",pair.name,".csv",sep = ""))
      
      # prepare for GO and KEGG
      DEGs$entrez <- mapIds(x = get(org.db),
                         keys = row.names(DEGs),
                         column = "ENTREZID",
                         keytype = "SYMBOL",
                         multiVals = "first")

      gene_matrix <- DEGs[,"avg_logFC"]
      names(gene_matrix) <- DEGs$entrez
      
      # GO
      GO.dir <- paste("./GO-",pair.name,sep = "")
      
      if ( !dir.exists(GO.dir) ) {
        dir.create(GO.dir)
      }
      
      for (genegroup in c("total","upregulated","downregulated")) {
        if (genegroup == "total") {
          gene_matrix_filtered <- gene_matrix
        }else if (genegroup == "upregulated") {
          gene_matrix_filtered <- gene_matrix[gene_matrix > 0]
        }else if (genegroup == "downregulated") {
          gene_matrix_filtered <- gene_matrix[gene_matrix < 0]
        }
        
        go_enrich <- enrichGO(gene = names(gene_matrix_filtered),
                            OrgDb = org.db, 
                            readable = T,
                            ont = "BP",
                            pvalueCutoff = 0.05, 
                            qvalueCutoff = 0.10)
        # Plot results
        if (!is.null(go_enrich)) {
            print(barplot(go_enrich, 
                drop = TRUE, 
                showCategory = 30, 
                title = paste("GO BP",genegroup,"DEGs of",pair.name,sep = " "),
                font.size = 8))
        
            write.csv(go_enrich,file = paste(GO.dir,"/GO-Biological-Process-using-",genegroup,"-genes-of-",pair.name,".csv",sep = ""))
        }
      }
      
      # KEGG
      KEGG.dir <- paste("./KEGG-",pair.name,sep = "")
       
      if ( !dir.exists(KEGG.dir) ) {
        dir.create(KEGG.dir)
      }
      
      for (genegroup in c("total","upregulated","downregulated")) {
        if (genegroup == "total") {
          gene_matrix_filtered <- gene_matrix
        }else if (genegroup == "upregulated") {
          gene_matrix_filtered <- gene_matrix[gene_matrix > 0]
        }else if (genegroup == "downregulated") {
          gene_matrix_filtered <- gene_matrix[gene_matrix < 0]
        }
        
        kegg_enrich <- enrichKEGG(gene = names(gene_matrix_filtered),
                                  keyType = "ncbi-geneid",
                                  organism = kegg.organism,
                                  pvalueCutoff = 0.05, 
                                  qvalueCutoff = 0.30)
        
        # Plot results
        if (!is.null(kegg_enrich)) {
          print(barplot(kegg_enrich, 
                drop = TRUE, 
                showCategory = 15, 
                title =  paste("KEGG Pathways",genegroup,"DEGs of",pair.name,sep = " "),
                font.size = 8))
        write.csv(kegg_enrich,file = paste(KEGG.dir,"/KEGG-Enrichment-Pathways-using-",genegroup,"-genes-of-",pair.name,".csv",sep = ""))
        
          # Plotting KEGG Pathways
        for (path_id in kegg_enrich@result$ID[kegg_enrich@result$p.adjust < 0.05]) {
          suppressMessages(pathview(gene.data = gene_matrix_filtered, 
                                    pathway.id = path_id, 
                                    species = kegg.organism))
          }
        }
      }
      
      pathview.files <- grep("pathview.png",list.files(),value = TRUE)
      if (length(pathview.files) != 0) {
        for (pathview.file in pathview.files) {
          files.move <- grep(gsub("pathview.png","",pathview.file),list.files(),value = TRUE)
          suppressMessages(file.move(files.move,KEGG.dir,overwrite = TRUE))
        }
      }
    }
  }
}
```


# Table: DEGs, GO and KEGG 

```{r}
pairName <- paste("DEGs-",all.samples[1],"-vs-",all.samples[2],sep = "")
```

## DEGs

```{r}
DEGs.file <- paste(pairName,'.csv',sep = "")
data.con <- read.csv(DEGs.file,row.names = 1)

datatable(data.con,
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip',buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>% formatSignif(c("p_val","avg_logFC","p_val_adj"),digits = 3)
```

## GO

```{r}
GO.path <- gsub("DEGs","GO",pairName)
```

### Total genes

```{r}
GO.up.file <- grep("total",list.files(GO.path),value = TRUE)
GO.up.path <- paste(GO.path,GO.up.file,sep = "/")
datatable(read.csv(GO.up.path),
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', scrollX = TRUE, buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>%
formatSignif(c("pvalue","p.adjust","qvalue"),digits = 3)
```

### Upregulated genes

```{r}
GO.up.file <- grep("upregulated",list.files(GO.path),value = TRUE)
GO.up.path <- paste(GO.path,GO.up.file,sep = "/")
datatable(read.csv(GO.up.path),
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', scrollX = TRUE, buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>%
formatSignif(c("pvalue","p.adjust","qvalue"),digits = 3)
```

### Downregulated genes

```{r}
GO.up.file <- grep("downregulated",list.files(GO.path),value = TRUE)
GO.up.path <- paste(GO.path,GO.up.file,sep = "/")
datatable(read.csv(GO.up.path),
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', scrollX = TRUE, buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>%
formatSignif(c("pvalue","p.adjust","qvalue"),digits = 3)
```

## KEGG

```{r}
GO.path <- gsub("DEGs","KEGG",pairName)
```

### Total genes

```{r}
GO.up.file <- grep("total",list.files(GO.path),value = TRUE)
GO.up.path <- paste(GO.path,GO.up.file,sep = "/")
datatable(read.csv(GO.up.path),
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', scrollX = TRUE, buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>%
formatSignif(c("pvalue","p.adjust","qvalue"),digits = 3)
```

### Upregulated genes

```{r}
GO.up.file <- grep("upregulated",list.files(GO.path),value = TRUE)
GO.up.path <- paste(GO.path,GO.up.file,sep = "/")
datatable(read.csv(GO.up.path),
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', scrollX = TRUE, buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>%
formatSignif(c("pvalue","p.adjust","qvalue"),digits = 3)
```

### Downregulated genes

```{r}
GO.up.file <- grep("downregulated",list.files(GO.path),value = TRUE)
GO.up.path <- paste(GO.path,GO.up.file,sep = "/")
datatable(read.csv(GO.up.path),
          extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', scrollX = TRUE, buttons = list('copy', 'print', list(extend = 'collection', buttons = c('csv', 'excel', 'pdf'), text = 'Download' ))))  %>%
formatSignif(c("pvalue","p.adjust","qvalue"),digits = 3)
```



