---
title: "Parameter-TEST"
author: "Zhang Yongchao"
date: "April 13, 2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(Seurat)
library(harmony)
library(purrr)
library(clustree)
library(dplyr)
```


```{r}
Variable.Features.numbers <- seq(2000,8000,by = 1000)
Run.Harmony.dims <- seq(20,100,by = 10)
markers <-  c("PTPRC","EPCAM","VWF","NRXN1","PDGFRA","PDGFRB")
qc.markers <- c("S.Score", "G2M.Score","percent.mt","nCount_RNA","scrublet","nFeature_RNA")
```

```{r}
cds <- readRDS("../Merge-Total-SeuratHarmony.rds")
```

```{r}
# nfeatures <- 2000
# dims <- 1:20
Plot.results <- list()
for (nfeatures in Variable.Features.numbers) {
  message("********** >>>>>> nFeatures: ",nfeatures," <<<<<<**********")
  Plot.features <- list()
  immune.combined <- suppressMessages(FindVariableFeatures(cds, selection.method = "vst", nfeatures = nfeatures))
  immune.combined <- suppressMessages(ScaleData(immune.combined, 
                               vars.to.regress = c("S.Score", "G2M.Score","percent.mt","nCount_RNA"), 
                               features = VariableFeatures(immune.combined),
                               verbose = FALSE))
  immune.combined <- suppressMessages(RunPCA(immune.combined, features = VariableFeatures(immune.combined), npcs = 100, verbose = FALSE))
  immune.combined <- suppressMessages(RunHarmony(immune.combined, group.by.vars = c("orig.ident","sex","subject")))
    
  for (dims in Run.Harmony.dims) {
    message("### >>>>>> nDims: ",dims," <<<<<< ...")
    immune.combined <- suppressMessages(RunUMAP(immune.combined, reduction = "harmony", dims = 1:dims, 
                                                umap.method = "umap-learn", metric = "correlation"))
    immune.combined <- suppressMessages(RunTSNE(immune.combined, reduction = "harmony", dims = 1:dims))
    immune.combined <- suppressMessages(FindNeighbors(immune.combined, reduction = "harmony", dims = 1:dims))
    immune.combined <- suppressMessages(FindClusters(immune.combined, resolution = c(0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6)))
    
    Plot.list <- list()
    Plot.list <- append(Plot.list,DimPlot(immune.combined,label = TRUE,combine = FALSE))
    Plot.list <- append(Plot.list,list(DimPlot(immune.combined,label = TRUE,split.by = "type",combine = FALSE)))
    
    Plot.list <- append(Plot.list,list(DimPlot(immune.combined,label = TRUE,group.by = "sex")))
    Plot.list <- append(Plot.list,list(DimPlot(immune.combined,label = TRUE,split.by = "subject")))
    
    Plot.list <- append(Plot.list,DimPlot(immune.combined,label = TRUE,combine = FALSE,reduction = "tsne"))
    Plot.list <- append(Plot.list,DimPlot(immune.combined,label = TRUE,combine = FALSE,split.by = "type",reduction = "tsne"))
    
    Plot.list <- append(Plot.list,list(DimPlot(immune.combined,label = TRUE,group.by = "sex",reduction = "tsne")))
    Plot.list <- append(Plot.list,list(DimPlot(immune.combined,label = TRUE,split.by = "subject",reduction = "tsne")))
    
    Plot.list <- append(Plot.list,list(FeaturePlot(immune.combined,features = markers,ncol = 3)))
    Plot.list <- append(Plot.list,list(FeaturePlot(immune.combined,features = qc.markers,ncol = 3)))
    
    tiff(file = paste("nFeatures-",nfeatures,"-nDims-",dims,"-markers.umap.tiff",sep = ""),width = 9,height = 6, units="in", res=300)
    # pdf(file = paste("nFeatures-",nfeatures,"-nDims-",dims,"-markers.umap.pdf",sep = ""),width = 9,height = 6)
    print(FeaturePlot(immune.combined,features = markers,ncol = 3) & NoLegend())
    dev.off()
    tiff(file = paste("nFeatures-",nfeatures,"-nDims-",dims,"-qc-markers.umap.tiff",sep = ""),width = 9,height = 6, units="in", res=300)
    print(FeaturePlot(immune.combined,features = qc.markers,ncol = 3) & NoLegend())
    dev.off()
    
    Plot.list <- append(Plot.list,list(clustree(immune.combined@meta.data, prefix = "RNA_snn_res.",return = "plot")))
    Plot.features <- append(Plot.features,list(Plot.list))
  }
  rm(immune.combined)
  Plot.results <- append(Plot.results,list(Plot.features))
}
```


```{r}
# saveRDS(Plot.results,file = "Parameter.test.Plots.rds") # too big, do not save!
```


```{r}
# Plot.list[[1]]
# Plot.list[[2]]
# Plot.list[[3]]
# Plot.list[[4]]
# 
# Plot.results <- list()
# Plot.results <- append(Plot.results, list(Plot.list))
# Plot.results <- append(Plot.results, list(Plot.list))
# 
# Plot.results[[1]][[1]]
# Plot.results[[2]][[2]]
# 
# length(Plot.results)
# 
# Plot.results[[1]][[1]][[1]]
```

```{r fig.height=6,fig.width=9}
library(patchwork)

pdf(file = "markers.umap.pdf",width = 9,height = 6)

for (i in 1:length(Variable.Features.numbers)) {
  for (j in 1:length(Run.Harmony.dims)) {
    print(Plot.results[[i]][[j]][[9]] +   plot_annotation( title = paste("nFeature - ",Variable.Features.numbers[i],"; nDims - ",Run.Harmony.dims[j])
    # subtitle = 'These 3 plots will reveal yet-untold secrets about our beloved data-set',
    # caption = 'Disclaimer: None of these plots are insightful'
    ) & NoLegend())
  }
}

dev.off()
```






