---
title: "Merge-all-by-seuratHarmony"
author: "Zhang Yongchao"
date: "November 18, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = -1,warning = -1)
```


```{r}
suppressMessages(library(dplyr)) 
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(cowplot))
suppressMessages(library(ggplot2))
suppressMessages(library(ggpubr))
suppressMessages(library(harmony))
library(purrr)
```

# import and merge

```{r}
immune.combined <- readRDS("./Merge-Total-SeuratHarmony.rds")
DimPlot(immune.combined,label = TRUE)
```

## test dims numbers

```{r}
immune.combined <- RunPCA(immune.combined, features = VariableFeatures(immune.combined), npcs = 100, verbose = FALSE)
immune.combined <- RunHarmony(immune.combined, group.by.vars = "orig.ident")
```

```{r}
test_dims <- function(cds,ndims){
  print(paste("*Processing dims:",ndims))
  cds  %>%
  RunUMAP(reduction = "harmony", dims = 1:ndims)  %>%
  RunTSNE(reduction = "harmony", dims = 1:ndims)  %>%
  FindNeighbors(reduction = "harmony", dims = 1:ndims) %>%
  FindClusters(resolution = 0.6)
}

obj.list <- suppressMessages(map(seq(20,100,by=10),function(x){test_dims(immune.combined,x)}))
```

```{r}
# saveRDS(obj.list,file = "test.temp.rds")
# obj.list <- readRDS("test.temp.rds")
```


```{r fig.width = 18,fig.height = 18}
plot.umap <- lapply(obj.list,function(x){
  Idents(x) <- "RNA_snn_res.0.6"
  return(DimPlot(x,label = TRUE) + NoLegend())
})

plot_grid(plotlist = plot.umap)
```

```{r fig.width = 18,fig.height = 18}
plot.umap <- lapply(obj.list,function(x){
  Idents(x) <- "RNA_snn_res.0.6"
  return(DimPlot(x,label = TRUE,reduction = "tsne") + NoLegend())
})

plot_grid(plotlist = plot.umap)
```

```{r fig.width = 18,fig.height = 18}
genes <- c("ACTA2","THY1","PDGFRA","PDGFRB","PTPRC","CD19","EPCAM","RGS5","MKI67")

plot.umap <- lapply(obj.list,function(x){
  Idents(x) <- "RNA_snn_res.0.6"
  return(FeaturePlot(x,features = genes,combine = FALSE))
})

map(1:length(plot.umap),function(x){ print(plot_grid(plotlist = plot.umap[[x]])) })

plot.umap <- lapply(obj.list,function(x){
  Idents(x) <- "RNA_snn_res.0.6"
  return(FeaturePlot(x,features = genes,combine = FALSE,reduction = "tsne"))
})

map(1:length(plot.umap),function(x){ print(plot_grid(plotlist = plot.umap[[x]])) })
```

```{r fig.width=8,fig.height=7}
# FeaturePlot(cds,features = "scrublet")
# DimPlot(cds,label = TRUE)
```

