---
title: "Step4.5 Ligand Receptor Analysis By CellPhoneDB"
author: "Zhang Yongchao"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    number_sections: TRUE
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
  warning = FALSE,
  collapse = TRUE,
  fig.align = "center")
```

```{r}
Rds.dir <- "./4.1-Replicates-Merged-Cells-Rds"
Results.dir <- "./4.5-Ligand-Receptor-Analysis/CellPhoneDB"
```

```{r}
suppressMessages(library(Seurat))
suppressMessages(library(biomaRt))
suppressMessages(library(dplyr))
```

# import data

```{r}
rds.file <- list.files(Rds.dir,pattern = ".rds$",full.names = TRUE)
cds <- readRDS(rds.file)
cds
```

# export data

```{r}
if ( !dir.exists(Results.dir)) {
  dir.create(Results.dir, recursive = TRUE)
}

nor.umi <- as.matrix(cds@assays$CellBender@data)
sample.meta <- data.frame(Cell = colnames(cds), cell_type = cds@meta.data$CellBender_snn_res.0.6)
```

##  mouse gene to human orthologs

```{r}
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
genes <- getBM(filters='mgi_symbol',
               attributes = c('ensembl_gene_id','mgi_symbol'),
               values = rownames(nor.umi),
               mart = mouse)
dim(genes)
```


```{r}
convertMouseGeneList <- function(x){
  require("biomaRt")
  human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
  genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = x , mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows = T)
  return(genesV2)
}
mgi_human <- convertMouseGeneList(genes$mgi_symbol)
dim(mgi_human)
```

```{r}
# Remove: a MGI symbol to many Human symbols
mgi_human <- mgi_human[!duplicated(mgi_human$MGI.symbol),]
# when many MGI symbols to one Human symbol, using the MGI symbol with max mean expression(equal to sum) in nor umi.
mgi_human.sum <- apply(nor.umi[mgi_human$MGI.symbol,],1,sum)
mgi_human$sum <- unname(mgi_human.sum)
# remove sum=zero
mgi_human <- mgi_human[mgi_human$sum != 0,]

mgi_human.filtered <-
  mgi_human %>%
  group_by(HGNC.symbol) %>%
  top_n(1,sum)
```

## filter nor umi and renaming gene name to human orthologs.

```{r}
nor.umi <- nor.umi[mgi_human.filtered$MGI.symbol,]
rownames(nor.umi) <- mgi_human.filtered$HGNC.symbol

nor.umi.new <- cbind(rownames(nor.umi),nor.umi)
colnames(nor.umi.new)[1] <- "Gene"
```


## save results

```{r}
write.table(sample.meta, file = paste0(Results.dir, "/cell.meta.txt"), quote = FALSE, row.names = FALSE, sep = "\t")
write.table(nor.umi.new, file = paste0(Results.dir, "/normalized.UMI.txt"), quote = FALSE, row.names = FALSE, sep = "\t")
```


# run CellPhoneDB

```{bash}
sh Step4.5-Run-CellPhoneDB.sh
```

# Session info

```{r}
sessionInfo()
```

