---
title: "Step3.3-Remove-Doublets-and-Reanalysis"
author: "Zhang Yongchao"
date: "February 26, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Seurat - Guided Clustering Tutorial

see: https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

```{r}
suppressMessages(library(dplyr)) 
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
library(ggplot2)
library(Matrix)
library(clustree)
```



## import data

```{r}
rds.files <- grep("annotated.scrublet.rds$",list.files(),value = TRUE)
obj.list <- lapply(rds.files, function(pbmc){
  message("* Processing sample: ",pbmc)
  cds <- readRDS(pbmc)
  return(cds)
})
obj.list
```

## remove doublets

```{r}
obj.list <- lapply(obj.list, function(cds){
  print(cds@project.name)
  cds <- cds[,colnames(cds)[cds@meta.data[,"doublet.srublet"] == "singlet"]]
  return(cds)
})
obj.list
```


## QC

```{r fig.width=5,fig.height=16}
# my own code for plots
# features <- c("nFeature_RNA", "nCount_RNA", "percent.mt","UMI.Non.mt")
# y.max = c(10000,1.5e5,100,1e5)
# for (i in 1:length(features)) {
#   VlnPlot.list <- lapply(obj.list, function(pbmc){ VlnPlot(pbmc, features = features[i], pt.size = 0.001,y.max = y.max[i], combine = FALSE) })
#   Aplot <- lapply(VlnPlot.list,function(x){ return(x[[1]] + NoLegend() + labs(x = "") + ggtitle("") + theme(axis.text.x = element_text(angle = 0,hjust = 0.5))) })
#   print(wrap_plots(Aplot,ncol = length(Aplot)) + plot_annotation(title = features[i],  theme = theme(plot.title = element_text(size = 18))))
# }

raw.merged <- merge(obj.list[[1]],obj.list[-1])
table(raw.merged@meta.data$orig.ident)
VlnPlot(raw.merged,features = c("nFeature_RNA", "nCount_RNA", "percent.mt","UMI.Non.mt"), ncol = 1,pt.size = 0.001, group.by = "orig.ident")
VlnPlot(raw.merged,features = c("nFeature_RNA", "nCount_RNA", "percent.mt","UMI.Non.mt"), ncol = 1,pt.size = 0, group.by = "orig.ident")
```


```{r}
hist(raw.merged@meta.data$nCount_RNA,breaks = 300,xlim = c(0,70000))
hist(raw.merged@meta.data$UMI.Non.mt,breaks = 300,xlim = c(0,20000))
hist(raw.merged@meta.data$nFeature_RNA,breaks = 70,xlim = c(0,9000))
hist(raw.merged@meta.data$nFeature_RNA,breaks = 100,xlim = c(0,1000))
hist(raw.merged@meta.data$percent.mt,breaks = 60)
```


```{r fig.width=12,fig.height=6}
lapply(obj.list, function(x){
  print(paste("*Processing sample: ",x@project.name,sep = ""))
  plot1 <- FeatureScatter(x, feature1 = "nCount_RNA", feature2 = "percent.mt")
  plot2 <- FeatureScatter(x, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
  print(plot1 + plot2)
  return(NULL)
})
```

## Modify old cluster names

```{r}
obj.list <- lapply(obj.list, function(cds){
  colnames(cds@meta.data)[grepl("^RNA_snn",colnames(cds@meta.data))] <- gsub("^RNA","old_with_doublets_RNA",colnames(cds@meta.data)[grepl("^RNA_snn",colnames(cds@meta.data))])
  return(cds)
})
```

## check sample sex info

```{r fig.width=8,fig.height=4}
VlnPlot(raw.merged,features = c("Xist"),group.by = "orig.ident",pt.size = 0.001)
```


## Normalizing the data

```{r}
obj.list <- lapply(obj.list, function(x){
  print(paste("*Processing sample: ",x@project.name,sep = ""))
  x <- NormalizeData(x, normalization.method = "LogNormalize", scale.factor = 10000)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 3000)
  s.genes <- readRDS("/data2/shared_data_backup/zhugl/scRNAseq-mouse-Intestine/Downstream-Analysis/Total-Embryo-SI-Sample/mouse.s.genes.rds")
  g2m.genes <- readRDS("/data2/shared_data_backup/zhugl/scRNAseq-mouse-Intestine/Downstream-Analysis/Total-Embryo-SI-Sample/mouse.g2m.genes.rds")
  x <- CellCycleScoring(x, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
  # all.genes <- rownames(x) # not dessary using all genes
  x <- ScaleData(x, vars.to.regress = c("percent.mt","nCount_RNA","S.Score", "G2M.Score"))
  x <- RunPCA(x, features = VariableFeatures(x))
  x <- RunUMAP(x, dims = 1:20)
  x <- RunTSNE(x, dims = 1:20)
  x <- FindNeighbors(x, dims = 1:20) %>% FindClusters(resolution = c(0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6))
  Idents(x) <- "RNA_snn_res.0.6"
  return(x)
})
```


```{r fig.width=8,fig.height=8}
lapply(obj.list, function(x){
  print(paste("*Processing sample: ",x@project.name,sep = ""))
  print(clustree(x@meta.data, prefix = "RNA_snn_res."))
  return(NULL)
})
```


```{r fig.width=12,fig.height=6}
lapply(obj.list, function(x){
  print(paste("*Processing sample: ",x@project.name,sep = ""))
  p1 <- DimPlot(x, reduction = "umap",label = TRUE)
  p2 <- DimPlot(x, reduction = "tsne",label = TRUE)
  print(p1+p2)
  return(NULL)
})
```

```{r fig.width=12,fig.height=8}
lapply(obj.list,function(x){
  print(paste("*Processing sample: ",x@project.name,sep = ""))
  p1 <- FeaturePlot(x,features = c("Ptprc","Epcam","Pdgfra"),label = TRUE,ncol = 3)
  p2 <- FeaturePlot(x,features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),label = TRUE,ncol = 3)
  print(p1 / p2)
  return(NULL)
})
```

```{r}
lapply(obj.list, function(x){
  print(paste("*Processing sample: ",x@project.name,sep = ""))
  sampleName <- paste(x@project.name,".doublets.removed.rds",sep = "")
  saveRDS(x,file = sampleName)
  return(NULL)
})
```
