---
title: "Step4.2 Downstream Analysis"
author: "Zhang Yongchao"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    number_sections: TRUE
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      collapse = TRUE,
                      warning = FALSE)
```

**Parameters:**

```{r}
Rds.dir <- "./3.3-Clean-Cells-Rds"
Results.dir <- "./3.4-Downstream-Analysis"
species <- "mouse" # or human, mouse
```


```{r}
kegg.organism <- switch(species,
                        drosophlia = "dme",
                        human = "hsa",
                        mouse = "mmu")
org.db <- switch(species,
                 drosophlia = "org.Dm.eg.db",
                 human = "org.Hs.eg.db",
                 mouse = "org.Mm.eg.db")
suppressMessages(library(clusterProfiler))
switch (species,
  drosophlia = suppressMessages(library(org.Dm.eg.db)),
  human = suppressMessages(library(org.Hs.eg.db)),
  mouse = suppressMessages(library(org.Mm.eg.db))
)
suppressMessages(library(pathview))
suppressMessages(library(filesstrings))
suppressMessages(library(Seurat))
suppressMessages(library(dplyr))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(pheatmap))
```

```{r fig.width=6,fig.height=6}
cds <- readRDS(list.files(Rds.dir,pattern = "rds$",full.names = TRUE))
cluster.resolution <- paste(DefaultAssay(cds),"_snn_res.0.6",sep = "")
Idents(cds) <- cluster.resolution
DimPlot(cds,label = TRUE) + NoLegend()
```

```{r}
# check if columns in meta.data are factor
# columns.factorization <- function(ADataFrame,columns = c(1:2)){
#   for (i in columns) {
#     ADataFrame[,i] <- as.factor(as.numeric(ADataFrame[,i]))
#   }
#   return(ADataFrame)
# }
# 
# cds@meta.data <- columns.factorization(cds@meta.data,columns = grep("_snn_res",colnames(cds@meta.data),value = TRUE))
```

# Find Cluster Markers

```{r}
save.dir <- paste(Results.dir,"/","Cluster-Markers",sep = "")
if ( !dir.exists(save.dir)) {
  dir.create(save.dir,recursive = TRUE)
}
save.file <- paste(save.dir,"/",basename(getwd()),"+",cluster.resolution,"+Default.csv",sep = "")
```

```{r}
if (!file.exists(save.file)) {
  cds.markers <- FindAllMarkers(cds, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
  write.csv(cds.markers,file = save.file)
}else{
  cds.markers <- read.csv(save.file,stringsAsFactors = FALSE,row.names = 1)
}

cds.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)
```

# GO And KEGG of the markers

```{r fig.width=10,fig.height=8}
for (i in levels(cds@active.ident)) {
  print(paste("Processing: ",i,sep = ""))
  markers.subset <- dplyr::filter(cds.markers,cluster == i)
  
  # prepare for GO and KEGG
  markers.subset$entrez <- mapIds(x = get(org.db),
                     keys = markers.subset$gene,
                     column = "ENTREZID",
                     keytype = "SYMBOL",
                     multiVals = "first")
  # GO
  GO.dir <-  paste(save.dir,"/GO",sep = "")
  if ( !dir.exists(GO.dir) ) {
      dir.create(GO.dir)
  }
  
  
  go_enrich <- enrichGO(gene = markers.subset$entrez,
                            OrgDb = org.db, 
                            readable = T,
                            ont = "BP",
                            pvalueCutoff = 0.05, 
                            qvalueCutoff = 0.10)
  # Plot results
  if (!is.null(go_enrich)) {
      print(barplot(go_enrich, 
          drop = TRUE, 
          showCategory = 30, 
          title = paste("GO BP - ",i,sep = ""),
          font.size = 8))
          write.csv(go_enrich,file = paste(GO.dir,"/GO-Biological-Process-using-markers-of-",i,".csv",sep = ""))
    }
      
  # KEGG
  KEGG.dir <-paste(save.dir,"/KEGG",sep = "")
   
  if ( !dir.exists(KEGG.dir) ) {
    dir.create(KEGG.dir)
  }
      

  kegg_enrich <- enrichKEGG(gene =  markers.subset$entrez,
                            keyType = "ncbi-geneid",
                            organism = kegg.organism,
                            pvalueCutoff = 0.05, 
                            qvalueCutoff = 0.30)
        
  # Plot results
  if (!is.null(kegg_enrich)) {
    print(barplot(kegg_enrich, 
          drop = TRUE, 
          showCategory = 15, 
          title =  paste("KEGG - ",i,sep = ""),
          font.size = 8))
  write.csv(kegg_enrich,file = paste(KEGG.dir,"/KEGG-Enrichment-Pathways-using-markers-of-",i,".csv",sep = ""))
 }
}
```



# Heatmap of top 10 markers

```{r fig.height=18,fig.width=20}
top10 <- cds.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
DoHeatmap(cds, features = top10$gene) + NoLegend()
```

# Dotplot of top 3 markers

```{r fig.width=21,fig.height=9}
top3 <- cds.markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_logFC)
DotPlot(cds,features = unique(top3$gene), group.by = cluster.resolution) + RotatedAxis()
```

# Cluster correlation

```{r fig.height=6,fig.width=7}
av.exp <- AverageExpression(cds)[[DefaultAssay(cds)]]
cor.exp <- as.data.frame(cor(av.exp,method = "pearson"))
pheatmap(cor.exp)
cor.exp <- as.data.frame(cor(av.exp,method = "spearman"))
pheatmap(cor.exp)
```

# Plot Customized Markers By Sample and Day

```{r fig.width=40,fig.height=32}
# save.file <- paste(Results.dir,"vlnplot-of-the-customized-markers-By-day.tiff",sep = "/")
# 
# # code reference: "Step 4.0 Plot Customized Markers in Batch mode"
# if( file.exists(plot.markers.file)){
#   markers <- read.csv(plot.markers.file,stringsAsFactors = FALSE)
#   colnames(markers) <- paste(markers[1,], markers[2,],sep = "_")
#   markers <- markers[-c(1,2),]
#   # remove columns without gnes
#   markers <- markers[,apply(markers == "",2,sum) != nrow(markers)]
#   # check markers
#   markers.genes <- unname(unlist(markers))
#   markers.genes <- markers.genes[markers.genes != ""]
#   markers.genes[!markers.genes %in% rownames(obj.list[[1]])]
#   markers.genes <- markers.genes[markers.genes %in% rownames(obj.list[[1]])]
#   # print(VlnPlot(cds,features = markers.genes,ncol = 10,pt.size = 0))
#   print(VlnPlot(cds,features = markers.genes,ncol = 10,pt.size = 0,group.by = "day"))
#   tiff(filename = save.file,width = 40,height = 32,res = 150,units = "in")
#   print(VlnPlot(cds,features = markers.genes,ncol = 10,pt.size = 0,group.by = "day"))
#   dev.off()
# }
```

# Session info

```{r}
sessionInfo()
```

