ViewBS MethOverRegion --region /home/xilab/software/msPIPE/msPIPE/reference/galGal6/galGal6.ncbiRefSeq.transcript.bed \
--sample D1-2_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D1-2 \
--sample D1-4_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D1-4 \
--sample D1-5_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D1-5 \
--sample D63-5_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D63-5 \
--sample D63-6_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D63-6 \
--sample D63-8_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D63-8 \
--sample D63-9_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D63-9 \
--sample D7-1_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D7-1 \
--sample D7-2_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D7-2 \
--sample D7-3_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D7-3 \
--sample D7-5_bismark_bt2_pe.deduplicated.CX_report.txt.gz,D7-5 \
--prefix MergedSingle --context CG
